name: CI
on:
  push:
    branches:
      - 'master'
    tags: 
      - 'v*'
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
      - name: Install node_modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
  style-check:
    name: Check code style
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
      - name: Run Prettier
        run: npm run prettier
      - name: Run EsLint
        run: npm run eslint
  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
      - name: Run build
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
  extract-commit-info:
    name: Extract commit info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
      version-without-v: ${{ steps.extract-version.outputs.version-without-v }}
    steps:
      - name: Extract version
        id: extract-version
        uses: battila7/get-version-action@v2
  test-step:
    name: test-step
    needs: extract-commit-info
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2