name: CICD
on:
  push:
    branches: ['master']
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
      - name: Install node_modules
        run: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
  extract-commit-info:
    name: Extract commit info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
      version-without-v: ${{ steps.extract-version.outputs.version-without-v }}
    steps:
      - name: Extract version
        id: extract-version
        uses: battila7/get-version-action@v2
  style-check:
    name: Check code style
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
      - name: Run Prettier
        run: npm run prettier
      - name: Run EsLint
        run: npm run eslint
  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
      - name: Run build
        run: npm run build