name: CICD
on:
  push:
    branches:
      - 'master'
    tags: 
      - 'v*'
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
      - name: Install node_modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
      - name: Run Prettier
        run: npm run prettier
      - name: Run EsLint
        run: npm run eslint
  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
      - name: Run build
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
  test:
    name: test
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
  release:
    name: Create release
    needs: [build, test, lint]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
      version-without-v: ${{ steps.extract-version.outputs.version-without-v }}
    steps:
      - name: Extract version
        id: extract-version
        uses: battila7/get-version-action@v2
      - name: Release
        id: create-release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.extract-version.outputs.version }}
          tag_name: ${{ steps.extract-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  npm-publish:
    name: Publish to NPM
    needs: [release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        id: cache-node-modules
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Publish 
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  homebrew-publish:
    name: Publish to Homebrew
    needs: [release, npm-publish]
    runs-on: ubuntu-latest
    steps:
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: harvey
          formula-path: Formula/harvey.rb
          homebrew-tap: simonrauch/homebrew-tap
          base-branch: main
          download-url: https://registry.npmjs.org/@simonrauch/harvey/-/harvey-${{ needs.release.outputs.version-without-v }}.tgz
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}