name: PR
on:
  pull_request:
  pull_request_target:
jobs:
  lint-pr:
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true